### PR TITLE
fix responsiveness

### PR DESCRIPTION
**Pull request by bhaskarSingh**
Closes #{1}

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [ yes] I have tested the changes locally and they are functional.
- [ yes] I ensure that my commit message is in imperative manner.
- [no ] I ensure that I have properly referenced the related issue.
- [no ] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [yes ] This pull request has a descriptive title. For example, `Add/Fix {Feature/Bug}`, not `Update README.md` or `Add new code`.
- [ okay] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Please attach screenshots at all major resolutions.

**Comment by bhaskarSingh** [comment]
screenshot 2018-12-02 at 5 24 59 pm
screenshot 2018-12-02 at 5 25 10 pm
screenshot 2018-12-02 at 5 25 23 pm
screenshot 2018-12-02 at 5 25 29 pm
screenshot 2018-12-02 at 5 25 36 pm
screenshot 2018-12-02 at 5 25 56 pm

**Review by anshumanv — CHANGES_REQUESTED** [review]
This is what I see when I hover on the last pokemon, I think it would make sense to make the popup cover the entire viewport when screen is smaller than a certain value.
image

**Comment by bhaskarSingh** [comment]
This is totally totally upto you, I think hover is okay, so what should I
do ?

**Comment by anshumanv** [comment]
> I think hover is okay

Can you see the last pokemon? I think we can just scale the popup to cover the entire screen, see if that fixes anything.

**Comment by Akshat-Jain** [comment]
Closing this PR as there haven't been any recent updates on it. Thanks!

**Pull request closed without merging**
