### PR TITLE
handle error gracefully incase no pokemon found

### PR DESCRIPTION
**Pull request by bhaskarSingh**
Closes #{3}

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [yes ] I have tested the changes locally and they are functional.
- [yes ] I ensure that my commit message is in imperative manner.
- [ yes] I ensure that I have properly referenced the related issue.
- [no ] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [ yes] This pull request has a descriptive title. For example, `Add/Fix {Feature/Bug}`, not `Update README.md` or `Add new code`.
- [ok ] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by anshumanv** [comment]
I'll check this tomorrow, thanks!

**Comment by anshumanv** [comment]
Will check this tomorrow thanks.

**Review by anshumanv — COMMENTED** [review]
While this is good, I think it doesn't make sense to display the pokemons which don't have evolution in the first place, can you research about removing them from the suggestions? :) Thanks

**Comment by bhaskarSingh** [comment]
what can be done here is that, I can remove pokemon without the evos key, that should solve the issue, should I go for it

**Comment by anshumanv** [comment]
It would be quite hectic to remove every single pokemon from the JSON file, you think you can do it?

**Comment by bhaskarSingh** [comment]
Well, we could just filter out the pokemons where there is no evolution or
previous evaluation is not present, I have already solved the issue will
push with the changes after I refactor the code

**Comment by bhaskarSingh** [comment]
I have made the changes, there are still few edge cases so have left the previous commit as it is

**Comment by anshumanv** [comment]
We still need pokemons which don't have an evo or prevo their gifs are available, we only need to remove those whose gifs aint available. Like `megaevolutions` etc. Please research a bit on it.

**Comment by Akshat-Jain** [comment]
Closing this PR as there haven't been any recent updates on it. Thanks!

**Pull request closed without merging**
